In [27]:
import pandas as pd
import numpy as np
from sklearn import svm,datasets,tree

data = datasets.load_iris()
data_points = data.data[:,:2]
target = data.target

x_train = data_points[:-10,:]
y_train = target[:-10]
x_test = data_points[-10:,:]
y_test = target[-10:]

tree_model = tree.DecisionTreeClassifier()
tree_model.fit(x_train,y_train)

print(tree_model.predict(x_test))





[1 1 1 2 2 1 1 2 1 1]


In [8]:
'''from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus

dot_data = StringIO()

export_graphviz(tree_model,out_file=dot_data,filled=True,rounded=True,special_characters = True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())
'''

InvocationException: GraphViz's executables not found

In [13]:
from sklearn.cluster import KMeans
from mpl_toolkits.mplot3d import axes3d
kmeans = KMeans(n_clusters=3)
kmeans = kmeans.fit(x_train)
label = kmeans.predict (x_train)
c = kmeans.cluster_centers_
print(c)




[[5.76   2.69  ]
 [5.006  3.418 ]
 [6.8425 3.06  ]]


In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
def random_forest_classifier(features, target):
    clf = RandomForestClassifier()
    clf.fit(features, target)
    return clf

model = random_forest_classifier(x_train, y_train)
predictions = model.predict(x_test)

print(confusion_matrix(y_test, predictions))



[[0 0]
 [4 6]]


In [25]:
from sklearn.naive_bayes import GaussianNB
training_model = GaussianNB()
training_model.fit(x_train,y_train)
predictions = training_model.predict(x_test)
print(predictions)
print(y_test)

[2 2 1 2 2 2 1 2 2 1]
[2 2 2 2 2 2 2 2 2 2]
